name: CI - MedControl

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache de dependências
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r datamedicamentos.txt

      - name: Instalar ferramentas de teste
        run: pip install flake8 pytest

      - name: Rodar lint
        run: flake8 src

      - name: Rodar testes
        run: pytest -v
